### ISSUE TITLE
Cannot change variable (React Native)

### ISSUE THREAD

**Issue by Gustl22** [brysgo/babel-plugin-inline-dotenv#138]
Hi there,
sorry if this isn't concerning this plugin, but I didn't experience it on any other place.
If I change the environment variable inside the `.env` file, the value isn't updated in the app itself.
I use React Native with Expo and debug the value inside IntelliJ (Ubuntu).
Tried following to update the value:

- `npm cache verify`
- `npm cache clean --force`
- set `api.cache(false);` in babel.config.js
- `npm start --clear` and `npm start --reset-cache`
- cleared App storage (of Expo) / uninstalled
- set option  `{unsafe: true}` in .babelrc / babel.config.js
- set option  `{systemVar: 'disable'}` in .babelrc / babel.config.js
- logout from PC
- ( no .cache folder in /node_modules, so cannot delete it (even not hidden) )

The only thing which worked was to completely restart my PC, so I definitely changed the right file.
Any solution to not need of restart after changing values?

**Comment by anjulalk** [comment]
Can confirm. I'm experiencing the same thing.

**Comment by anjulalk** [comment]
It looks like you need to clear Metro cache for the changes to reflect. This is the same issue #13 
For Expo, this solved my issues: `expo start -c`

**Comment by Gustl22** [comment]
Hey @anjulalk, yeah that solved it!

For better explanation: I already tried `npm start --clear` which I thought is the same as `expo start --clear` or `expo start -c`. But thats not the case. 

To pass arguments to npm scripts (in package.json) you have to separate them with two hyphens: `npm start -- -c`.

So for IntelliJ Debug Configuration I came up with this: 

![Screenshot from 2020-10-05 17-38-29](https://user-images.githubusercontent.com/18537755/95101343-532ab880-0732-11eb-9bca-87fc42b9dee4.png)
