### ISSUE TITLE
Add option for plain replacement

### ISSUE THREAD

**Issue by joh-klein** [brysgo/babel-plugin-inline-dotenv#16]
Would you consider adding an option to switch between this replacement:

`process && process.env && process.env.MY_VARIABLE || 'value assigned to variable in dotenv'`

and this:

`'value assigned to variable in dotenv'`

I want to use this plugin in an AWS Lambda context and I would rather have the "short form" replacement.

Thanks for considering it!

**Comment by joh-klein** [comment]
For the time being, I did what I needed with [patch-package](https://www.npmjs.com/package/patch-package). The resulting `.patch` file looks like this (this is for v1.1.2):

```
patch-package
--- a/node_modules/babel-plugin-inline-dotenv/src/index.js
+++ b/node_modules/babel-plugin-inline-dotenv/src/index.js
@@ -25,15 +25,7 @@ module.exports = function (options) {
             var i = t.identifier;
             var le = t.logicalExpression;
 
-            path.replaceWith(
-              le('||', 
-                le('&&', 
-                  le('&&', i('process'), me(i('process'), i('env'))),
-                  me(i('process.env'), i(name))
-                ), 
-                t.valueToNode(value)
-              )
-            );
+            path.replaceWith(t.valueToNode(value));
           }
         }
       }
```

**Comment by brysgo** [comment]
👍 glad you were able to solve this for your use case, I would consider adding it as an option
