### ISSUE TITLE
Version 1.3.1 requires .env file to be present

### ISSUE THREAD

**Issue by d4rky-pl** [brysgo/babel-plugin-inline-dotenv#28]
395ed0a7a7d39089ab8de13ceadc68aab91c5d95 introduced `readFileSync` which causes the plugin to crash if `.env` is not present instead of gracefully ignoring it

**Comment by brysgo** [comment]
Yikes, adding this to my todo list for a patch

**Comment by Platane** [comment]
My bad, dotenv does silently fallback to not using the .env if it's not found
