### ISSUE TITLE
Notice that this won't work with babel-loader cacheDirectory

### ISSUE THREAD

**Issue by einarlove** [brysgo/babel-plugin-inline-dotenv#7]
If you use babel-loader in Webpack and use the cacheDirectory, you won't get updated files if you change a value with `ENV=VALUE npm run start`. Maybe put a notice in readme?

**Comment by brysgo** [comment]
@einarlove - that is a great idea, I usually blow away my cache dir when I change my environment (not the best solution)

**Comment by simenbrekken** [comment]
This also applies outside of Webpack with something like `API_URL=http://localhost:8081/api npm run dev` where `API_URL` is never picked up

**Comment by brysgo** [comment]
Yep, any time you are caching your babel output.

**Comment by mattbrunetti** [comment]
Path to the cacheDirectory: `./node_modules/.cache/babel-loader`

Clear it with `rm -rf ./node_modules/.cache/babel-loader`

**Comment by antoinerousseau** [comment]
could the babel-loader caching be disabled by this plugin?

**Comment by brysgo** [comment]
@antoinerousseau - that is an interesting proposition, is this something that babel-loader allows?
