### ISSUE TITLE
support variable expansion

### ISSUE THREAD

**Issue by jzimmek** [brysgo/babel-plugin-inline-dotenv#9]
Hi, I would like to use variable expansion in our .env files.

Seems like dotenv already supports this by a companion package: https://github.com/motdotla/dotenv-expand

Would be great if this babel plugin would support this out-of-the-box or as a configuration option.

Is this something you would consider as a PR?

**Comment by brysgo** [comment]
@jzimmek - I would most certainly consider a PR for it.

Would love if it:
1. Were an optional dependency
2. Had a test
3. Didn't include a breaking change

Thanks for contributing :-)

**Comment by brysgo** [comment]
Published as of v1.1.2 -- thanks @jzimmek
